/*1*/SELECT nombre FROM producto;
/*2*/SELECT nombre, producto.precio FROM producto;
/*3*/DESCRIBE producto;
/*4*/SELECT nombre, precio AS precio_€, TRUNCATE(producto.precio * 1.0685, 2) AS precio_USD FROM producto;
/*5*/SELECT nombre AS 'nom de producto', precio AS euros, TRUNCATE(producto.precio * 1.0685, 2) AS dòlars FROM producto;
/*6*/SELECT upper(nombre) AS producto, precio FROM producto;
/*7*/SELECT lower(nombre) AS producto, precio FROM producto;
/*8*/SELECT nombre, upper(SUBSTRING(nombre, 1,2)) AS iniciales FROM fabricante;
/*9*/SELECT nombre AS producto, round(precio) AS 'precio redondeado' FROM producto;
/*10*/SELECT nombre AS producto, TRUNCATE(producto.precio, 0) AS 'precio truncado' FROM producto;
/*11*/SELECT codigo_fabricante FROM producto;
/*12*/SELECT DISTINCT codigo_fabricante FROM producto;
/*13*/SELECT nombre FROM fabricante ORDER BY nombre;
/*14*/SELECT nombre FROM fabricante ORDER BY nombre DESC;
/*15*/SELECT nombre AS 'producto (ordenado alfabetico)' FROM producto ORDER BY nombre;
SELECT nombre AS 'producto (ordenado precio desc)'FROM producto ORDER BY precio DESC;
/*16*/SELECT * FROM fabricante LIMIT 5;
/*17*/SELECT * FROM fabricante LIMIT 3, 2;
/*18*/SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
/*19*/SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
/*20*/SELECT nombre AS producto FROM producto WHERE codigo_fabricante = 2;
/*21*/SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto AS p, fabricante AS f WHERE p.codigo_fabricante = f.codigo;
/*22*/SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre;
/*23*/SELECT p.codigo AS codigo_producto, p.nombre AS producto, p.codigo_fabricante, f.nombre AS fabricante FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo;
/*24*/SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE precio = (SELECT MIN(precio) FROM producto);
/*25*/SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE precio = (SELECT MAX(precio) FROM producto);
/*26*/SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo');
/*27*/SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Crucial') AND precio > 200;
/*28*/SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus') OR codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard') OR codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Seagate');
/*29*/SELECT nombre FROM producto WHERE codigo_fabricante IN (SELECT codigo FROM fabricante WHERE nombre = 'Asus' OR nombre = 'Hewlett-Packard' OR nombre = 'Seagate');
/*30*/SELECT nombre, precio FROM producto WHERE codigo_fabricante IN (SELECT codigo FROM fabricante WHERE nombre LIKE '%e');
/*31*/SELECT nombre, precio FROM producto WHERE codigo_fabricante IN (SELECT codigo FROM fabricante WHERE nombre LIKE '%w%');
/*32*/SELECT p.nombre AS producto, precio, f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE precio >= 180 ORDER BY precio DESC;
SELECT p.nombre AS producto, precio, f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE precio >= 180 ORDER BY p.nombre;
/*33*/SELECT codigo, nombre AS fabricante FROM fabricante WHERE codigo IN (SELECT DISTINCT codigo_fabricante FROM producto);
/*34*/SELECT f.nombre AS fabricante, p.nombre AS producto FROM fabricante AS f LEFT JOIN producto AS p ON p.codigo_fabricante = f.codigo ORDER BY f.nombre;
/*35*/SELECT f.nombre AS fabricante, p.nombre AS producto FROM fabricante AS f LEFT JOIN producto AS p ON p.codigo_fabricante = f.codigo WHERE p.nombre IS NULL;
/*36*/SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo from fabricante WHERE nombre = 'Lenovo');
/*37*/SELECT * FROM producto WHERE precio = (SELECT max(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo from fabricante WHERE nombre = 'Lenovo'));
/*38*/SELECT p.nombre FROM producto AS p INNER JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo' ORDER BY p.precio DESC LIMIT 1;
/*39*/SELECT p.nombre FROM producto AS p INNER JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre = 'Hewlett-Packard' ORDER BY p.precio LIMIT 1;
/*40*/SELECT nombre FROM producto WHERE precio >= (SELECT max(precio) FROM producto AS p INNER JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo');
/*41*/SELECT nombre FROM producto WHERE precio >= (SELECT AVG(precio) FROM producto AS p INNER JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus');