SELECT nombre FROM producto;
SELECT nombre, producto.precio FROM producto;
DESCRIBE producto;
SELECT nombre, precio AS precio_€, TRUNCATE(producto.precio * 1.0685, 2) AS precio_USD FROM producto;
SELECT nombre AS 'nom de producto', precio AS euros, TRUNCATE(producto.precio * 1.0685, 2) AS dòlars FROM producto;
SELECT upper(nombre) AS producto, precio FROM producto;
SELECT lower(nombre) AS producto, precio FROM producto;
SELECT nombre, upper(SUBSTRING(nombre, 1,2)) AS iniciales FROM fabricante;
SELECT nombre AS producto, round(precio) AS 'precio redondeado' FROM producto;
SELECT nombre AS producto, TRUNCATE(producto.precio, 0) AS 'precio truncado' FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre AS 'producto (ordenado alfabetico)' FROM producto ORDER BY nombre;
SELECT nombre AS 'producto (ordenado precio desc)'FROM producto ORDER BY precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3, 2;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre AS producto FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto AS p, fabricante AS f WHERE p.codigo_fabricante = f.codigo;
SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre;
SELECT p.codigo AS codigo_producto, p.nombre AS producto, p.codigo_fabricante, f.nombre AS fabricante FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE precio = (SELECT MIN(precio) FROM producto);
SELECT p.nombre AS producto, precio, f.nombre AS fabricante FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE precio = (SELECT MAX(precio) FROM producto);
SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo');
SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Crucial') AND precio > 200;
SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus') OR codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard') OR codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Seagate');
SELECT nombre FROM producto WHERE codigo_fabricante IN (SELECT codigo FROM fabricante WHERE nombre = 'Asus' OR nombre = 'Hewlett-Packard' OR nombre = 'Seagate');
SELECT nombre, precio FROM producto WHERE codigo_fabricante IN (SELECT codigo FROM fabricante WHERE nombre LIKE '%e');
SELECT nombre, precio FROM producto WHERE codigo_fabricante IN (SELECT codigo FROM fabricante WHERE nombre LIKE '%w%');
SELECT p.nombre AS producto, precio, f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE precio >= 180 ORDER BY precio DESC;
SELECT p.nombre AS producto, precio, f.nombre FROM producto AS p INNER JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE precio >= 180 ORDER BY p.nombre;
SELECT codigo, nombre AS fabricante FROM fabricante WHERE codigo IN (SELECT DISTINCT codigo_fabricante FROM producto);
SELECT f.nombre AS fabricante, p.nombre AS producto FROM fabricante AS f LEFT JOIN producto AS p ON p.codigo_fabricante = f.codigo ORDER BY f.nombre;
SELECT f.nombre AS fabricante, p.nombre AS producto FROM fabricante AS f LEFT JOIN producto AS p ON p.codigo_fabricante = f.codigo WHERE p.nombre IS NULL;
SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo from fabricante WHERE nombre = 'Lenovo');
SELECT * FROM producto WHERE precio = (SELECT max(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo from fabricante WHERE nombre = 'Lenovo'));
SELECT p.nombre FROM producto AS p INNER JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo' ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre FROM producto AS p INNER JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre = 'Hewlett-Packard' ORDER BY p.precio LIMIT 1;
SELECT nombre FROM producto WHERE precio >= (SELECT max(precio) FROM producto AS p INNER JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo');
SELECT nombre FROM producto WHERE precio >= (SELECT AVG(precio) FROM producto AS p INNER JOIN fabricante AS f ON  p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus');